'use strict';
const menuButton = document.querySelector('.menu-toggle');
const navigation = document.querySelector('.nav');
function closeMenu() { menuButton.setAttribute('aria-expanded', 'false'); menuButton.setAttribute('aria-label', 'Открыть меню'); navigation.classList.remove('is-open'); }
menuButton.addEventListener('click', () => { const open = menuButton.getAttribute('aria-expanded') !== 'true'; menuButton.setAttribute('aria-expanded', String(open)); menuButton.setAttribute('aria-label', open ? 'Закрыть меню' : 'Открыть меню'); navigation.classList.toggle('is-open', open); });
navigation.addEventListener('click', event => { if (event.target.closest('a')) closeMenu(); });
document.addEventListener('keydown', event => { if (event.key === 'Escape') closeMenu(); });
window.addEventListener('resize', () => { if (window.innerWidth > 800) closeMenu(); });
const tabs = [...document.querySelectorAll('[data-filter]')];
function activateTab(tab) { tabs.forEach(item => { const active = item === tab; item.setAttribute('aria-selected', String(active)); item.tabIndex = active ? 0 : -1; }); document.querySelectorAll('[data-category]').forEach(card => { card.hidden = tab.dataset.filter !== 'all' && card.dataset.category !== tab.dataset.filter; }); document.querySelector('#direction-panel').setAttribute('aria-labelledby', tab.id); }
tabs.forEach((tab, index) => { tab.addEventListener('click', () => activateTab(tab)); tab.addEventListener('keydown', event => { let next; if (event.key === 'ArrowRight') next = (index + 1) % tabs.length; if (event.key === 'ArrowLeft') next = (index - 1 + tabs.length) % tabs.length; if (event.key === 'Home') next = 0; if (event.key === 'End') next = tabs.length - 1; if (next !== undefined) { event.preventDefault(); activateTab(tabs[next]); tabs[next].focus(); } }); });
const modal = document.querySelector('#info-modal');
const modalBody = document.querySelector('#modal-body');
let lastFocus;
function openDialog(dialog) { lastFocus = document.activeElement; dialog.showModal(); document.body.classList.add('modal-open'); }
document.querySelectorAll('dialog').forEach(dialog => { dialog.querySelector('.modal-close').addEventListener('click', () => dialog.close()); dialog.addEventListener('click', event => { if (event.target !== dialog) return; const rect = dialog.getBoundingClientRect(); if (event.clientX < rect.left || event.clientX > rect.right || event.clientY < rect.top || event.clientY > rect.bottom) dialog.close(); }); dialog.addEventListener('close', () => { document.body.classList.remove('modal-open'); if (lastFocus?.isConnected) lastFocus.focus(); }); });
const details = {
  boxing: { label: 'БОЛЬШЕ ДВИЖЕНИЯ', title: 'ВКЛЮЧИ ХАРАКТЕР.', text: 'Бокс и кроссфит указаны среди направлений в официальном Instagram Life Fitness Astana. Выбирай то, что ближе твоему характеру и целям.', list: ['Бокс — техника и работа над выносливостью', 'Кроссфит — разнообразие функциональных тренировок', 'Расписание, уровень подготовки и формат участия уточняйте у клуба'], interest: 'Бокс и кроссфит' },
  kids: { label: 'ДЛЯ ВСЕЙ СЕМЬИ', title: 'СВОЙ КЛУБ. С ДЕТСТВА.', text: 'В Life Fitness Astana есть детский клуб — он указан в официальном Instagram. Познакомьтесь с возможностями для семейного посещения.', list: ['Детский клуб', 'Бассейны для взрослых и детей', 'Возраст, занятия и условия детского абонемента уточняйте у администратора'], interest: 'Семейное посещение' },
  gym: { label: '01 / СИЛА И ВЫНОСЛИВОСТЬ', title: 'ТВОЯ СЛЕДУЮЩАЯ ПОБЕДА.', text: 'Тренажёрный зал — пространство, где маленькие шаги превращаются в заметный прогресс. Выбирай свой темп и двигайся к своей цели.', list: ['Тренажёрный зал входит в безлимитный абонемент', 'В клубе представлены бокс и кроссфит', 'Условия персональных тренировок уточняйте у клуба'], interest: 'Тренажёрный зал' },
  pool: { label: '02 / ДВИЖЕНИЕ И ЛЁГКОСТЬ', title: 'В СВОЁМ ПОТОКЕ.', text: 'Поменяй городской ритм на ритм воды. Плавание для активной тренировки или спокойного завершения дня.', list: ['На сайте клуба указаны 4 вида бассейна', 'Бассейны для взрослых и детей', 'Расписание и условия детских занятий — у администратора'], interest: 'Бассейны и аквазона' },
  group: { label: '03 / ЭНЕРГИЯ ВМЕСТЕ', title: 'НАЙДИ СВОИХ.', text: 'Когда рядом люди с похожими целями, начать проще, а двигаться вперёд — интереснее. Найди занятие под своё настроение.', list: ['Групповые программы в абонементе', 'Танцевальные классы и Antigravity yoga', 'Актуальное расписание — в приложении клуба'], interest: 'Групповые программы' },
  spa: { label: '04 / ВОССТАНОВЛЕНИЕ', title: 'ВРЕМЯ ВЫДОХНУТЬ.', text: 'Дай себе время на паузу. Заверши тренировку в тёплой атмосфере сауны или турецкого хамама.', list: ['Финская сауна', 'Инфракрасная сауна и турецкий хамам', 'Халат и полотенце входят в абонемент'], interest: 'Сауны и хамам' }
};
document.querySelectorAll('[data-detail]').forEach(button => button.addEventListener('click', () => { const detail = details[button.dataset.detail]; modalBody.innerHTML = `<span class="eyebrow">${detail.label}</span><h2 id="modal-title">${detail.title}</h2><p>${detail.text}</p><ul>${detail.list.map(item => `<li>${item}</li>`).join('')}</ul><button class="button" id="detail-enquire">Узнать об абонементе <span><svg class="icon icon-arrow-up-right" viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="M5 19 19 5M5 5h14v14"/></svg></span></button>`; openDialog(modal); document.querySelector('#detail-enquire').addEventListener('click', () => renderEnquiry(detail.interest)); }));
function renderEnquiry(interest) { modalBody.innerHTML = `<span class="eyebrow">ТВОЙ ПЕРВЫЙ ШАГ</span><h2 id="modal-title">НАЧНЁМ С ТЕБЯ.</h2><p>Выбери, что тебе интересно. Подготовим сообщение — ты сможешь отправить его менеджеру клуба в WhatsApp.</p><label for="interest">Меня интересует</label><select id="interest"><option>Годовой безлимит</option><option>Первое знакомство с клубом</option><option>Тренажёрный зал</option><option>Бассейны и аквазона</option><option>Групповые программы</option><option>Сауны и хамам</option><option>Семейное посещение</option><option>Бокс и кроссфит</option><option>Рассрочка</option></select><a class="button" id="whatsapp-link" href="https://wa.me/77019531465" target="_blank" rel="noopener noreferrer">Продолжить в WhatsApp <span><svg class="icon icon-arrow-up-right" viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="M5 19 19 5M5 5h14v14"/></svg></span></a><p class="privacy-note">Откроется WhatsApp с подготовленным текстом. До отправки сообщения заявка не создаётся; этот сайт не собирает персональные данные.</p>`; const select = document.querySelector('#interest'); if ([...select.options].some(option => option.value === interest)) select.value = interest; const update = () => { const message = `Здравствуйте! Меня интересует ${select.value.toLowerCase()} в Life Fitness Astana. Подскажите, пожалуйста, актуальную стоимость и условия посещения.`; document.querySelector('#whatsapp-link').href = `https://wa.me/77019531465?text=${encodeURIComponent(message)}`; }; select.addEventListener('change', update); update(); if (modal.open) select.focus(); }
document.querySelectorAll('[data-enquire]').forEach(button => button.addEventListener('click', () => { renderEnquiry(button.dataset.enquire); openDialog(modal); }));
const gallery = document.querySelector('#gallery-modal');
const photos = [{ src: 'assets/gym.jpg', title: 'Пространство для твоего роста' }, { src: 'assets/training.jpg', title: 'Сильнее с каждой тренировкой' }, { src: 'assets/pool.jpg', title: 'Поймай свой поток' }, { src: 'assets/group.jpg', title: 'Энергия, которая объединяет' }, { src: 'assets/sauna.jpg', title: 'Время восстановить силы' }];
let photoIndex = 0;
function showPhoto(index) { photoIndex = (index + photos.length) % photos.length; document.querySelector('#gallery-image').src = photos[photoIndex].src; document.querySelector('#gallery-image').alt = photos[photoIndex].title; document.querySelector('#gallery-title').textContent = photos[photoIndex].title; document.querySelector('#gallery-count').textContent = `0${photoIndex + 1} / 0${photos.length}`; }
document.querySelectorAll('[data-gallery]').forEach(button => button.addEventListener('click', () => { showPhoto(Number(button.dataset.gallery)); openDialog(gallery); }));
document.querySelector('#gallery-prev').addEventListener('click', () => showPhoto(photoIndex - 1));
document.querySelector('#gallery-next').addEventListener('click', () => showPhoto(photoIndex + 1));
gallery.addEventListener('keydown', event => { if (event.key === 'ArrowLeft' || event.key === 'ArrowRight') { event.preventDefault(); showPhoto(photoIndex + (event.key === 'ArrowRight' ? 1 : -1)); } });
